---
title: "Resume"
output: 
  html_document:
    toc: true
    toc_float: true
---

## Academic qualifications and Professional experience

### EDUCATION

#### **Columbia University, Mailman School of Public Health, New York, NY**  				          May 2023

**Master of Public Health in Epidemiology, Certificate in Applied Biostatistics & Public Health Data Science** GPA: 4.05

  * Relevant Coursework:  Machine Learning, Data Science, FDA- New Drug Development, Geographic Information Surveillance (GIS), Applied Regression, Survival Analysis, Cox-model Analysis, Qualitative and Quantitative Research Methods,  Analysis of categorical data, Program planning and evaluation, , Health Economics,  Determinants of health, Global and developmental perspectives, Health Economics, Global and Developmental Perspectives, Global Mental Health
  
  * Course Projects:
    * Developed a website using R studio and R shiny: Utilized advanced statistical techniques and conducted a stepwise AIC regression to evaluate association of Bechdel test scores with movie budget, profits and IMDB ratings. Collaborated with a team to develop a website for the final project of Data Science. https://sopochkon1.github.io/sheroes_finalproject.github.io/About.html
    * Association between Smoking and Cholesterol levels: Examined whether cholesterol is associated with the number of years an individual has smoked by conducting logistic regression using data from NHANES III data. Analysis was performed using SAS 9.4	
    * Impact of Policy Change on Infant Mortality: Assessed the effects of fiscal decentralization in India on Infant mortality rates. Collected survey data and census data for a “pre/post” analysis. Leveraged Excel for data visualization 
    * Used CLAIMS tool to systematically assess and summarize the study’s strength of causal inference, including generalizability, potential confounders, and methods used
    * Created a map using QGIS to analyze 10-year change in the median earnings gap by gender across states in USA.

#### **Goenka Research Institute Of Dental Sciences**                                       September 2019

**Bachelor of Dental Surgery (BDS)**

* Graduated among top 5% of the class
* Organized Dental check-up camps and awareness campaigns in rural areas, Cultural committee member , management committee of CDE programs


### PROFESSIONAL EXPERIENCE
#### Mailman School Of Public Health
**Graduate Research Assistant, New York, USA**	July 2022- present

  * Conducted a targetted literature review search to identify clinical trials and publications that utilised biomarkers to assess alcohol use with an intervention component
  * Processed and manipulated data to produce a descriptive statistics report evaluating biomarker and self-report measures for
alcohol use with the findings to be published in a forthcoming scoping review
  * Contributed to the development of future publications by conducting a comprehensive review of ~200 articles and clinical trials,
meticulously extracting data from 80 articles and clinical trials for data compilation and analyses.

**Data Research Analyst Intern**	June-September 2022

  * Analyzed trends of marijuana use and risk perceptions among 1,359,169 high-school students in the U.S. by running a piecewise regression model from 1991-2020 using Monitoring The Future(MTF) survey Database
  * Independently conducted data compilation, coding, statistical analysis, and data visualization using SAS 9.4 and R 4.2.1


#### Janvikas
**GDA program coordinator – Health Care, Gujarat, India**	March - August 2021

  * Facilitated and coordinated healthcare workforce training program for 50-60 economically disadvantaged students in Gujarat, improving access to resources and employment opportunities, resulting in successful employment in  prestigious hospitals
  * Designed and implemented a survey to analyze healthcare facilities and availability of resources, providing critical data to inform development of a telemedicine program aimed at improving health status of rural Gujarat
  * Effectively tutored over 100 participants, conducted lectures and designed a study guidebook, all within a 6-month timeframe


#### Shraddhadeep Dental Clinic
**Associate Dentist, Gujarat, India**	October 2019 - September 2020

  * Participated in routine clinical procedures like diagnosis, treatment planning and performing minor surgical procedures   * Performed duties involving patient reception, scheduling appointments, and overlooking inventory

#### Goenka Research Institute of Dental Sciences 
**Dental Intern, Gujarat, India**	September2018 - October2019 

  * Successfully diagnosed and treated over 1000 patients during a 12-month internship program and effectively managed patient database of over 5000 patients
  * Collected and analyzed data for OSMF prevalence in rural areas, developed infographics on common prevalent dental conditions in villages 
  
### COMMUNITY SERVICE & INVOLVEMENT

#### Kalpaseva Arogya Kendra (NGO)	October 2019 - March 2020
  * Efficiently managed high volume of patients and provided free diagnosis and treatment to patients at Kalpaseva Arogya Kendra

### SKILLS AND CERTIFICATIONS
* Strong knowledge of MS Office and GitHub
* Statistical and research software : SAS (expert), R (intermediate), STATA (beginner)
* Certifications: ICH-GCP certification, HIPAA certification, Registered Dentist GDC




